server:
  port: 9095

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${JDBC_DATABASE_PASSWORD}
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL94Dialect

#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    password: root
#    url: jdbc:mysql://localhost:3306/productService?useSSL=false
#    username: root
#  jpa:
#    show-sql: true
#    hibernate:
#        ddl-auto: update
#    properties:
#        hibernate:
#            dialect: org.hibernate.dialect.MySQL5Dialect


#eureka:
#  client:
#    serviceUrl: 
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
